import json
import re

def correct_json(text: str) -> dict:
    """
    Utility to correct common JSON errors generated by models:
    - Missing closing brackets/braces
    - Trailing commas
    - Markdown formatting (e.g., ```json ... ```)
    """
    if not isinstance(text, str):
        return {}
        
    text = text.strip()
    
    # Remove markdown code blocks if present
    if text.startswith('```'):
        text = re.sub(r'^```(?:json)?\n?', '', text)
        text = re.sub(r'\n?```$', '', text)
        text = text.strip()

    # Try normal parse
    try:
        parsed = json.loads(text)
        return parsed if isinstance(parsed, dict) else {}
    except json.JSONDecodeError:
        pass

    # Fix trailing commas
    text = re.sub(r',\s*([\]}])', r'\1', text)

    # Balance brackets and braces
    stack = []
    in_string = False
    escape = False
    
    for char in text:
        if escape:
            escape = False
            continue
        if char == '\\':
            escape = True
            continue
        if char == '"':
            in_string = not in_string
            continue
        if not in_string:
            if char == '{':
                stack.append('}')
            elif char == '[':
                stack.append(']')
            elif char == '}':
                if stack and stack[-1] == '}':
                    stack.pop()
            elif char == ']':
                if stack and stack[-1] == ']':
                    stack.pop()
    
    if in_string:
        text += '"'
    
    # Append missing closing brackets/braces
    fixed_text = text
    while stack:
        fixed_text += stack.pop()
        
    try:
        parsed = json.loads(fixed_text)
        return parsed if isinstance(parsed, dict) else {}
    except json.JSONDecodeError:
        pass
        
    # Fallback to extracting the first valid JSON object
    start = text.find('{')
    if start != -1:
        depth = 0
        in_str = False
        esc = False
        for i, ch in enumerate(text[start:], start=start):
            if esc:
                esc = False
                continue
            if ch == '\\' and in_str:
                esc = True
                continue
            if ch == '"':
                in_str = not in_str
                continue
            if in_str:
                continue
            if ch == '{':
                depth += 1
            elif ch == '}':
                depth -= 1
                if depth == 0:
                    candidate = text[start:i + 1]
                    try:
                        parsed = json.loads(candidate)
                        return parsed if isinstance(parsed, dict) else {}
                    except json.JSONDecodeError:
                        return {}
    return {}
